version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "8334:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000                       # для app.listen
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./src:/app/src      # 🔁 Монтируем исходники
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./keys:/app/keys
      - ./storage:/app/storage
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6334:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app-network

  # prometheus:
  #   image: prom/prometheus
  #   container_name: ${PROM_CONTAINER_NAME}
  #   volumes:
  #     - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "${PROM_PORT}:9090"
  #   networks:
  #     - app-network  

  # loki:
  #   image: grafana/loki:2.9.3
  #   container_name: ${LOKI_CONTAINER_NAME}
  #   ports:
  #     - "${LOKI_PORT}:3100"

  #   volumes:
  #     - ./config/loki/config.yaml:/etc/loki/config.yaml
  #     - ./loki-data/loki/chunks:/loki/chunks
  #     - ./loki-data/loki/index:/loki/index
  #     - ./loki-data/loki/cache:/loki/boltdb-cache
  #     - ./loki-data/loki/compactor:/loki/compactor
  #     - ./loki-data/loki/wal:/loki/wal
  #   command: -config.file=/etc/loki/config.yaml 
  #   networks:
  #     - app-network  

  # promtail:
  #   image: grafana/promtail:2.9.3
  #   container_name: ${PROMTAIL_CONTAINER_NAME}
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /etc/machine-id:/etc/machine-id:ro
  #     - ./config/promtail/config.yaml:/etc/promtail/config.yaml
  #   command: -config.file=/etc/promtail/config.yaml
  #   networks:
  #     - app-network  


  # grafana:
  #   image: grafana/grafana
  #   container_name: ${GRAFANA_CONTAINER_NAME}
  #   ports:
  #     - "${GRAFANA_PORT}:3000"
  #   volumes:
  #     - ./logs/data/grafana:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
  #   networks:
  #     - app-network  
 
networks:
  app-network:
    driver: bridge
# volumes:
#   loki-data:    


# version: '3.8'

# services:
#   redis:
#     image: redis
#     container_name: redis
#     ports:
#       - "6379:6379"
