server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
  
    static_configs:
      - targets: 
        - localhost
        labels:
          job: nest-app
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - labels:
          container_name:
      - match:
          selector: '{container_name="nest-api"}'
          stages:
            - json:
                expressions:
                  level: level
                  msg: msg
