import type { ParamDescriptor } from './registry.types';

/**
 * Часть реестра: рёбра воронки, наклон «качество → исход», цикл сделки и
 * план на день (план 4.1, 4.4, 4.8, 4.9). Собирается в `registry.const.ts`.
 */
export const AI_ANALYTICS_FUNNEL_PARAMS = [
    {
        code: 'theta_edge_rate',
        title: 'Ребро как интенсивность (до сцепки со сделкой)',
        scope: 'manager',
        source: 'estimated',
        unit: 'событий на вход ребра',
        defaultValue: 0,
        range: [0, 10],
        phase: 2,
        breaksSeries: false,
        estimator:
            'Gamma-Poisson: (s̃ + κ_k·μ_lk)/(ñ + κ_k) по агрегатам месяца',
        minN: 30,
        gate: 'доля сцепки звонок → сделка ниже deal_chain_min_pct',
        intervalKind: 'gamma',
        estimand: 'rate',
        description:
            'Пока звонки не сцеплены со сделками, ребро считается интенсивностью на агрегатах result_total (например, КП на 100 уникальных презентаций месяца), где s ≤ n не гарантируется, а интервал берётся гамма-отношением.',
    },
    {
        code: 'theta_edge_prob',
        title: 'Ребро как вероятность продвижения эпизода',
        scope: 'manager',
        source: 'estimated',
        unit: 'доля',
        defaultValue: 0,
        range: [0, 1],
        phase: 3,
        breaksSeries: false,
        estimator: 'Beta-биномиал по эпизодам сделки: (s̃ + κ_k·μ_lk)/(ñ + κ_k)',
        minN: 30,
        gate: 'сцепка ≥ deal_chain_min_pct два пересчёта подряд',
        intervalKind: 'wilson',
        estimand: 'prob',
        description:
            'После сцепки то же ребро становится вероятностью продвижения эпизода с собственными числителем, знаменателем и историей: ряды интенсивностей в апостериоры вероятностей не подмешиваются.',
    },
    {
        code: 'deal_chain_min_pct',
        title: 'Порог сцепки звонок → сделка для перехода на вероятности',
        scope: 'portal',
        source: 'configured',
        unit: '%',
        defaultValue: 80,
        range: [60, 95],
        phase: 2,
        breaksSeries: true,
        description:
            'Вход гистерезиса: при доле сцепленных звонков ниже порога рёбра считаются интенсивностями. Переключение портала на вероятности — только вперёд и рвёт сравнимость рядов ребра.',
    },
    {
        code: 'deal_chain_exit_pct',
        title: 'Порог выхода из режима вероятностей',
        scope: 'portal',
        source: 'configured',
        unit: '%',
        defaultValue: 70,
        range: [50, 90],
        phase: 2,
        breaksSeries: false,
        description:
            'Нижняя точка гистерезиса: режим вероятностей удерживается, пока сцепка не упала ниже этого значения — иначе портал бы «дрожал» между двумя оцениваемыми величинами.',
    },
    {
        code: 'beta_quality_near_within',
        title: 'Наклон «качество → ближний исход», внутри менеджера',
        scope: 'portal',
        source: 'estimated',
        unit: 'логит на балл качества',
        defaultValue: 0,
        range: [0, 0.5],
        phase: 4,
        breaksSeries: false,
        estimator:
            'logit со случайным эффектом менеджера, центрирование Мундлака',
        minN: 10,
        gate: 'n_w ≥ 10 звонков корзины в неделю (практически только пул)',
        estimand: 'within',
        description:
            'Связь недельных колебаний качества одного менеджера с ближним исходом эпизода. На одном портале почти не оценивается и до гейта показывается как «не оценено».',
    },
    {
        code: 'beta_quality_near_between',
        title: 'Наклон «качество → ближний исход», между менеджерами',
        scope: 'portal',
        source: 'estimated',
        unit: 'логит на балл качества',
        defaultValue: 0,
        range: [0, 0.5],
        phase: 4,
        breaksSeries: false,
        estimator:
            'logit со случайным эффектом менеджера, центрирование Мундлака',
        minN: 350,
        gate: 'beta_gate_se и калибровочный наклон, накрывающий 1',
        estimand: 'between',
        description:
            'Различия менеджеров по среднему качеству против их исходов. Показывается вместе с within: если знаки расходятся, UI пишет об этом прямо.',
    },
    {
        code: 'beta_quality_near_pooled',
        title: 'Наклон «качество → ближний исход», объединённый',
        scope: 'portal',
        source: 'estimated',
        unit: 'логит на балл качества',
        defaultValue: 0,
        range: [0, 0.5],
        phase: 4,
        breaksSeries: false,
        estimator:
            'logit без центрирования, усадка к пулу при согласии порталов',
        minN: 700,
        gate: 'beta_gate_se два месячных пересчёта подряд (гистерезис)',
        estimand: 'pooled',
        description:
            'Оценка, по которой берётся гейт публикации: всё прикладное считается на шкале вероятности p̂(S), а не на шкале связи — экспонента допустима только для редкого исхода.',
    },
    {
        code: 'beta_gate_se',
        title: 'Гейт точности β по стандартной ошибке',
        scope: 'global',
        source: 'configured',
        unit: 'логит на балл качества',
        defaultValue: 0.07,
        range: [0.03, 0.15],
        phase: 4,
        breaksSeries: false,
        description:
            'β переводится в режим «по данным», когда SE(β̂_pooled) не выше порога и 90 %-интервал наклона калибровки накрывает 1, два пересчёта подряд. Ориентир: ≈ 700–900 презентаций.',
    },
    {
        code: 'pool_min_portals_beta',
        title: 'Минимум порталов для собственной оценки τ² пула β',
        scope: 'global',
        source: 'configured',
        unit: 'порталов',
        defaultValue: 8,
        range: [3, 10],
        phase: 4,
        breaksSeries: false,
        description:
            'Пока порталов с согласием меньше, применяется полное объединение с проверкой гетерогенности (Q Кокрана, I²) и слабоинформативным half-normal прайором τ, результат помечается как гибрид.',
    },
    {
        code: 'cycle_median_days',
        title: 'Медиана цикла «презентация → оплата»',
        scope: 'portal',
        source: 'hybrid',
        unit: 'календарных дней',
        defaultValue: 28,
        range: [7, 180],
        phase: 2,
        breaksSeries: false,
        prior: 28,
        estimator: 'Каплан–Майер лага среди проданных эпизодов, w = n/(n + 20)',
        minN: 30,
        gate: '≥ 30 закрытых продаж (≥ 100 — собственная таблица F(d))',
        description:
            'До оценки F(d) зрелость пайплайна считается экспонентой с этой медианой: F̄(D_rem) усредняется по оставшимся дням месяца, а не берётся в конечной точке.',
    },
    {
        code: 'lag_window_sale_days',
        title: 'Окно атрибуции продажи',
        scope: 'portal',
        source: 'hybrid',
        unit: 'календарных дней',
        defaultValue: 60,
        range: [30, 180],
        phase: 3,
        breaksSeries: true,
        prior: 60,
        estimator: 'P90 лага «активность → продажа» по stagehistory',
        minN: 100,
        gate: '≥ 100 продаж со сцепкой',
        description:
            'За сколько дней после активности продажа ещё относится к ней. Смена окна меняет числитель рёбер и рвёт сравнимость истории.',
    },
    {
        code: 'f_min',
        title: 'Нижняя граница зрелости F̄(D_rem) в обратной задаче',
        scope: 'global',
        source: 'configured',
        unit: 'доля',
        defaultValue: 0.1,
        range: [0.05, 0.3],
        phase: 2,
        breaksSeries: false,
        description:
            'Защита от деления на почти ноль в конце месяца: N_req = max(0, G − Y₀ − λ_pipe)/(c_mk·F̄(D_rem)) считается с F̄ не ниже порога, иначе требуемый объём улетает в бесконечность.',
    },
    {
        code: 'plan_day_ceiling',
        title: 'Потолок плана на день',
        scope: 'portal',
        source: 'configured',
        unit: 'множитель к плану, делённому на рабочие дни',
        defaultValue: 1.5,
        range: [1, 2.5],
        phase: 2,
        breaksSeries: false,
        description:
            'Менеджер видит одно число D_τ = max(0, (план − сделано)/дней осталось), но не выше потолка: догонять месячный недобор за три дня — не план, а демотивация.',
    },
] as const satisfies readonly ParamDescriptor[];
