import type { AiAnalyticsParamCode } from './registry.const';
import { AI_EDGE_CODES, edgeCode, muEdgeCode } from './registry.edges.const';
import {
    AI_CAP_ACTIVITY_TYPES,
    AI_DURATION_ACTIVITY_TYPES,
} from './registry.enums.const';
import { capCode, durationMinCode } from './registry.activity.const';
import { AI_SKILL_INDEX_EDGES, skillWeightCode } from './registry.pool.const';

/**
 * Коды сводного реестра анкеты Ж (`ai-sales-analytics-inputs.md`, раздел Ж):
 * 84 строки в порядке таблицы. Приёмка формулируется через покрытие — для
 * каждого кода анкеты есть ≥ 1 код реестра (план §2.1), а не через
 * «реестр содержит 84 кода».
 */
export const AI_ANALYTICS_ANKETA_CODES = [
    'time_zone',
    'workweek',
    'holidays',
    'absences',
    'fte_share',
    'min_workdays_month',
    'day_hours',
    'level',
    'since',
    'status_left_at',
    'tenure_gates',
    'level_hysteresis',
    'skill_index_weights',
    'training_min_presentations',
    'target_sales_by_level',
    'target_override',
    'plan_snapshot_history',
    'productive_call_definition',
    'presentation_canon',
    'hot_client_definition',
    'decision_stages',
    'min_duration_sec',
    'min_duration_sec_by_type',
    'invoice_nesting',
    'call_done_includes_site_come_call',
    'funnel_edges',
    'scoring_applicability',
    'scoring_caps',
    'scoring_stop_words',
    'quality_form_sections',
    'forget_lambda',
    'kappa_activity_days',
    'kappa_edge',
    'kappa_level',
    'kappa_portal_to_global',
    'mu_edge',
    'theta_manager_edge',
    'rate_manager_activity',
    'm_score_pseudo_n',
    'sigma_llm',
    'icc_quality',
    's_ref',
    'portal_quality_hypothesis',
    'beta_quality_near',
    'beta_quality_sale',
    'beta_section',
    'spline_knots_S',
    'beta_gate',
    'lead_kind_strata',
    'lead_mix_stratum',
    'W_attribution_days',
    'cycle_median_days',
    'lag_cdf_F',
    'f_min',
    'check_lognormal',
    'ramp_tau0_months',
    'ramp_volume_boost',
    'season_index',
    'portal_events',
    'cap_level_activity',
    'activity_duration_min',
    'coaching_hours_section',
    'plan_day_ceiling',
    's_req_max',
    'stage_sla',
    'n_min_thresholds',
    'z_compare',
    'delta_prac',
    'trend_params',
    'control_chart_params',
    'goodhart_detector',
    'audit_samples',
    'lever_params',
    'evidence_gate',
    'experiment_design_params',
    'attention_params',
    'alert_params',
    'rop_user_ids',
    'product_pool',
    'pool_min_portals',
    'calibration_gates',
    'dq_gates',
    'calc_version',
    'params_version',
] as const;

/** Код анкеты Ж. */
export type AiAnalyticsAnketaCode = (typeof AI_ANALYTICS_ANKETA_CODES)[number];

/** Непустой список кодов реестра. */
type ParamCodes = readonly [AiAnalyticsParamCode, ...AiAnalyticsParamCode[]];

const EDGE_RATE_CODES = AI_EDGE_CODES.map(edge => edgeCode(edge, 'rate'));
const EDGE_PROB_CODES = AI_EDGE_CODES.map(edge => edgeCode(edge, 'prob'));

/**
 * Соответствие «код анкеты Ж → коды реестра» (план §2.1). Составные строки
 * анкеты расщеплены на скалярные коды; имена расщеплений приняты в реестре
 * и менять их нельзя. Спека проверяет: ключи = 84 кода, у каждого ≥ 1 код
 * реестра, каждый упомянутый код существует в `AI_ANALYTICS_PARAMS`.
 */
export const AI_ANALYTICS_PARAM_MAPPING: Readonly<
    Record<AiAnalyticsAnketaCode, ParamCodes>
> = {
    time_zone: ['time_zone'],
    workweek: ['workweek'],
    holidays: ['holidays'],
    absences: ['absences', 'absence_proxy_min_run'],
    fte_share: ['fte_share', 'fte_share_default'],
    min_workdays_month: ['min_workdays_month'],
    day_hours: ['day_hours'],
    level: ['level'],
    since: ['since'],
    status_left_at: ['manager_status', 'manager_left_at'],
    tenure_gates: ['tenure_gates', 'tenure_bands'],
    level_hysteresis: ['level_hysteresis_up', 'level_hysteresis_down'],
    skill_index_weights: [
        skillWeightCode('quality'),
        ...AI_SKILL_INDEX_EDGES.map(edge => skillWeightCode(edge)),
    ],
    training_min_presentations: ['training_min_presentations'],
    target_sales_by_level: ['target_sales_by_level'],
    target_override: ['target_override'],
    plan_snapshot_history: ['plan_snapshot_history'],
    productive_call_definition: ['productive_call_definition'],
    presentation_canon: ['presentation_canon', 'presentation_confirmed_only'],
    hot_client_definition: ['hot_client_definition', 'hot_client_colors'],
    decision_stages: ['decision_stages'],
    min_duration_sec: ['min_duration_sec'],
    min_duration_sec_by_type: ['min_duration_sec_by_type'],
    invoice_nesting: ['invoice_nesting'],
    call_done_includes_site_come_call: ['call_done_includes_site_come_call'],
    funnel_edges: ['funnel_edges'],
    scoring_applicability: ['scoring_applicability'],
    scoring_caps: ['scoring_caps'],
    scoring_stop_words: ['scoring_stop_words'],
    quality_form_sections: ['quality_form_sections'],
    forget_lambda: ['forget_lambda'],
    kappa_activity_days: ['kappa_activity_days'],
    kappa_edge: ['kappa_edge_early', 'kappa_edge_late', 'kappa_max'],
    kappa_level: ['kappa_layer_ratio', 'kappa_boot_ratio'],
    kappa_portal_to_global: ['kappa_portal_to_global'],
    mu_edge: [
        muEdgeCode(AI_EDGE_CODES[0]),
        ...AI_EDGE_CODES.slice(1).map(edge => muEdgeCode(edge)),
    ],
    theta_manager_edge: [
        'theta_edge_rate',
        'theta_edge_prob',
        ...EDGE_RATE_CODES,
        ...EDGE_PROB_CODES,
    ],
    rate_manager_activity: ['rate_manager_activity', 'overdispersion_default'],
    m_score_pseudo_n: ['m_s_default', 'm_s_max'],
    sigma_llm: ['sigma_llm_default', 'retest_budget_calls'],
    icc_quality: ['icc_quality', 'icc_form'],
    s_ref: ['s_ref'],
    portal_quality_hypothesis: ['portal_quality_hypothesis'],
    beta_quality_near: [
        'beta_quality_near_within',
        'beta_quality_near_between',
        'beta_quality_near_pooled',
    ],
    beta_quality_sale: ['beta_quality_sale'],
    beta_section: ['beta_section'],
    spline_knots_S: ['spline_knots_s'],
    beta_gate: [
        'beta_gate_se',
        'pool_min_portals_beta',
        'tau_prior_sd',
        'kappa_beta',
    ],
    lead_kind_strata: ['lead_kind_strata'],
    lead_mix_stratum: ['lead_mix_stratum'],
    W_attribution_days: ['lag_window_near_days', 'lag_window_sale_days'],
    cycle_median_days: ['cycle_median_days'],
    lag_cdf_F: ['lag_cdf_F', 'cif_sale_inf', 'pipeline_estimand'],
    f_min: ['f_min'],
    check_lognormal: ['check_lognormal_m', 'check_lognormal_v'],
    ramp_tau0_months: ['ramp_tau0_months'],
    ramp_volume_boost: ['ramp_volume_boost'],
    season_index: ['season_index', 'kappa_season_years'],
    portal_events: ['portal_events'],
    cap_level_activity: [
        'cap_level_activity',
        'cap_quantile',
        ...AI_CAP_ACTIVITY_TYPES.map(type => capCode(type)),
    ],
    activity_duration_min: [
        durationMinCode(AI_DURATION_ACTIVITY_TYPES[0]),
        ...AI_DURATION_ACTIVITY_TYPES.slice(1).map(type =>
            durationMinCode(type),
        ),
    ],
    coaching_hours_section: ['coaching_hours_section'],
    plan_day_ceiling: ['plan_day_ceiling'],
    s_req_max: ['s_req_max'],
    stage_sla: [
        'sla_refine_days',
        'sla_decision_days',
        'sla_money_await_days',
        'sla_first_touch_min',
    ],
    n_min_thresholds: [
        'n_min_none',
        'n_min_ok_score',
        'n_min_ok_rate',
        'n_min_rating',
    ],
    z_compare: ['z_compare'],
    delta_prac: ['delta_prac_pct', 'delta_prac_score'],
    trend_params: [
        'trend_window_calls',
        'trend_ewma_short',
        'trend_ewma_long',
        'trend_sigma_k',
        'trend_fwer',
    ],
    control_chart_params: ['xmr_sigma', 'xmr_run_length', 'cusum_k', 'cusum_h'],
    goodhart_detector: [
        'goodhart_drop',
        'goodhart_window_months',
        'next_step_confirm_min',
    ],
    audit_samples: ['audit_samples_per_month', 'audit_samples_per_manager'],
    lever_params: [
        'lever_max',
        'lever_lb_level',
        'lever_min_section_calls',
        'lever_samples',
    ],
    evidence_gate: ['evidence_gate_advice', 'evidence_gate_card'],
    experiment_design_params: [
        'experiments_enabled',
        'experiment_crossover_weeks',
        'experiment_washout_weeks',
        'experiment_wedge_months',
    ],
    attention_params: [
        'attention_max_items',
        'attention_discipline_pct',
        'attention_n_plan_min',
        'attention_no_next_step_streak',
    ],
    alert_params: [
        'alert_max_per_day',
        'alert_quiet_from_hour',
        'alert_quiet_to_hour',
    ],
    rop_user_ids: ['rop_user_ids'],
    product_pool: ['product_line', 'product_pool_months', 'pool_opt_in'],
    pool_min_portals: ['pool_min_portals'],
    calibration_gates: [
        'calibration_min_months',
        'calibration_min_presentations',
        'calibration_comparable_weeks',
    ],
    dq_gates: [
        'dq_manager_coverage_pct',
        'dq_noise_share_pct',
        'dq_type_f1_min',
        'dq_crm_ai_kappa_min',
        'dq_score_icc_min',
        'dq_timestamp_leak_max',
        'dq_stage_history_months',
        'dq_placebo_max',
        'deal_chain_min_pct',
        'deal_chain_exit_pct',
    ],
    calc_version: ['calc_version'],
    params_version: ['params_version'],
};
