import type { ParamDescriptor } from './registry.types';

/**
 * Часть реестра: гейты качества данных, готовности и детекторы рядов
 * (план §2.1: dq_gates, calibration_gates, trend_params,
 * control_chart_params, goodhart_detector). Все — решения политики
 * честности, поэтому `configured`. Собирается в `registry.const.ts`.
 */
export const AI_ANALYTICS_DQ_PARAMS = [
    {
        code: 'dq_manager_coverage_pct',
        title: 'Покрытие звонков менеджером',
        scope: 'global',
        source: 'configured',
        unit: '%',
        defaultValue: 95,
        range: [80, 100],
        phase: 0,
        breaksSeries: false,
        description:
            'Доля звонков с определённым менеджером, ниже которой портал не проходит гейт данных (расщепление dq_gates): без атрибуции нормы считаются не на тех людях.',
    },
    {
        code: 'dq_noise_share_pct',
        title: 'Доля шума в разборах',
        scope: 'global',
        source: 'configured',
        unit: '%',
        defaultValue: 10,
        range: [0, 30],
        phase: 0,
        breaksSeries: false,
        description:
            'Максимальная доля разборов с типом other + irrelevant (расщепление dq_gates): выше — классификатор или порог длительности настроены плохо, слой качества не публикуется.',
    },
    {
        code: 'dq_type_f1_min',
        title: 'Минимальный F1 классификатора типов',
        scope: 'global',
        source: 'configured',
        unit: 'F1',
        defaultValue: 0.8,
        range: [0.5, 1],
        phase: 0,
        breaksSeries: false,
        description:
            'Гейт качества типизации звонков на golden set (расщепление dq_gates): ниже — рёбра по типам не публикуются, потому что знаменатели размыты.',
    },
    {
        code: 'dq_crm_ai_kappa_min',
        title: 'Минимальная каппа согласия CRM × AI',
        scope: 'global',
        source: 'configured',
        unit: 'каппа Коэна',
        defaultValue: 0.6,
        range: [0.3, 0.9],
        phase: 0,
        breaksSeries: false,
        description:
            'Согласие типа звонка по CRM-приору и по классификатору (расщепление dq_gates): ниже порога расхождения показываются в санити, а не прячутся усреднением.',
    },
    {
        code: 'dq_score_icc_min',
        title: 'Минимальная ICC оценщика',
        scope: 'global',
        source: 'configured',
        unit: 'коэффициент',
        defaultValue: 0.7,
        range: [0.6, 0.9],
        phase: 3,
        breaksSeries: false,
        description:
            'Порог надёжности icc_quality / icc_form, ниже которого эффекты качества и рычаг quality скрыты (расщепление dq_gates).',
    },
    {
        code: 'dq_timestamp_leak_max',
        title: 'Максимальная доля утечек времени',
        scope: 'global',
        source: 'configured',
        unit: 'доля',
        defaultValue: 0.05,
        range: [0.01, 0.15],
        phase: 2,
        breaksSeries: false,
        description:
            'Доля эпизодов, у которых событие исхода датировано раньше активности (аудит меток времени): выше порога сцепка звонок → сделка считается ненадёжной и рёбра остаются интенсивностями.',
    },
    {
        code: 'dq_stage_history_months',
        title: 'Глубина истории стадий',
        scope: 'global',
        source: 'configured',
        unit: 'месяцев',
        defaultValue: 3,
        range: [1, 12],
        phase: 0,
        breaksSeries: false,
        description:
            'Сколько месяцев stagehistory нужно для SLA-фактов, окон атрибуции и эпизодов (расщепление dq_gates); меньше — пайплайн считается только по текущим стадиям.',
    },
    {
        code: 'dq_placebo_max',
        title: 'Максимальная плацебо-корреляция',
        scope: 'global',
        source: 'configured',
        unit: 'коэффициент корреляции',
        defaultValue: 0.3,
        range: [0.1, 0.5],
        phase: 0,
        breaksSeries: false,
        description:
            'Корреляция качества с исходом, который качество менять не может (плацебо-тест): выше порога связь «качество → исход» помечается как артефакт отбора (расщепление dq_gates).',
    },
    {
        code: 'calibration_min_months',
        title: 'Срок калибровки портала',
        scope: 'global',
        source: 'configured',
        unit: 'месяцев',
        defaultValue: 3,
        range: [2, 6],
        phase: 1,
        breaksSeries: false,
        description:
            'Месяцев истории разборов до выхода витрины из режима calibration (расщепление calibration_gates): раньше показываются только описательные карточки.',
    },
    {
        code: 'calibration_min_presentations',
        title: 'Минимум презентаций для норм',
        scope: 'global',
        source: 'configured',
        unit: 'разобранных презентаций',
        defaultValue: 100,
        range: [60, 200],
        phase: 1,
        breaksSeries: false,
        description:
            'Гейт L2 режима norms (расщепление calibration_gates): пока подтверждённых презентаций меньше, нормы полосы стажа не публикуются, а причина пишется как norms-presentations-below.',
    },
    {
        code: 'calibration_comparable_weeks',
        title: 'Минимум недель сопоставимой истории',
        scope: 'global',
        source: 'configured',
        unit: 'недель',
        defaultValue: 4,
        range: [2, 8],
        phase: 1,
        breaksSeries: false,
        description:
            'Сколько недель после comparableFrom нужно, чтобы тренды и сравнения показывались (расщепление calibration_gates); смена версии обнуляет счётчик.',
    },
    {
        code: 'trend_ewma_short',
        title: 'α короткой EWMA тренда качества',
        scope: 'global',
        source: 'configured',
        unit: 'коэффициент сглаживания',
        defaultValue: 0.3,
        range: [0.05, 0.5],
        phase: 3,
        breaksSeries: false,
        description:
            'Вес нового разбора в короткой экспоненциальной скользящей средней (расщепление trend_params): чем выше, тем быстрее тренд реагирует и тем больше ложных сигналов.',
    },
    {
        code: 'trend_ewma_long',
        title: 'α длинной EWMA тренда качества',
        scope: 'global',
        source: 'configured',
        unit: 'коэффициент сглаживания',
        defaultValue: 0.1,
        range: [0.05, 0.5],
        phase: 3,
        breaksSeries: false,
        description:
            'Вес нового разбора в длинной EWMA (расщепление trend_params); флаг тренда ставится по расхождению короткой и длинной средних на k·σ_personal.',
    },
    {
        code: 'trend_fwer',
        title: 'FWER перестановочной калибровки трендов',
        scope: 'global',
        source: 'configured',
        unit: 'вероятность',
        defaultValue: 0.1,
        range: [0.05, 0.2],
        phase: 3,
        breaksSeries: false,
        description:
            'Допустимая вероятность хотя бы одного ложного флага тренда на семейство менеджеров (расщепление trend_params); порог k калибруется циркулярным блочным перестановочным тестом.',
    },
    {
        code: 'xmr_sigma',
        title: 'Множитель XmR-карты',
        scope: 'global',
        source: 'configured',
        unit: 'множитель к средней скользящей амплитуде',
        defaultValue: 2.66,
        range: [2, 3.5],
        phase: 1,
        breaksSeries: false,
        description:
            'Границы XmR-карты: центр ± множитель × mR̄ (расщепление control_chart_params); 2,66 соответствует трём сигмам при оценке разброса по скользящей амплитуде.',
    },
    {
        code: 'xmr_run_length',
        title: 'Серия XmR по одну сторону от центра',
        scope: 'global',
        source: 'configured',
        unit: 'точек подряд',
        defaultValue: 7,
        range: [5, 9],
        phase: 1,
        breaksSeries: false,
        description:
            'Сколько точек подряд по одну сторону от центра дают сигнал «run» без выхода за границы (расщепление control_chart_params).',
    },
    {
        code: 'cusum_k',
        title: 'Допуск CUSUM',
        scope: 'global',
        source: 'configured',
        unit: 'сигм',
        defaultValue: 0.5,
        range: [0.25, 1],
        phase: 1,
        breaksSeries: false,
        description:
            'Половина сдвига в сигмах, который CUSUM на пуассоновских остатках должен обнаруживать (расщепление control_chart_params); 0,5 настроен на сдвиг в одну сигму.',
    },
    {
        code: 'cusum_h',
        title: 'Порог сигнала CUSUM',
        scope: 'global',
        source: 'configured',
        unit: 'сигм',
        defaultValue: 4,
        range: [3, 6],
        phase: 1,
        breaksSeries: false,
        description:
            'Накопленная сумма остатков, при которой CUSUM ставит сигнал (расщепление control_chart_params); h = 4 при k = 0,5 даёт среднюю длину серии без сдвига около 170 точек.',
    },
    {
        code: 'goodhart_drop',
        title: 'Относительное падение конверсии для Goodhart',
        scope: 'global',
        source: 'configured',
        unit: 'доля',
        defaultValue: 0.3,
        range: [0.15, 0.5],
        phase: 3,
        breaksSeries: false,
        description:
            'На сколько должна упасть нижняя граница апостериора следующего ребра при росте балла, чтобы детектор Goodhart поставил сигнал «балл делают, а не зарабатывают» (расщепление goodhart_detector).',
    },
    {
        code: 'golden_kappa_min',
        title: 'Минимальная каппа надёжного поля разбора',
        scope: 'global',
        source: 'configured',
        unit: 'каппа',
        defaultValue: 0.4,
        range: [0.2, 0.8],
        phase: 3,
        breaksSeries: false,
        description:
            'Каппа Коэна между двумя прогонами одной версии промпта (test-retest, отчёт согласия), ниже которой категориальное поле разбора (тип звонка, исход, приоритет) помечается «ненадёжно» в блоке «Как считаем» — число по нему скрывается по правилу n_min, а не подаётся как «значимо».',
    },
] as const satisfies readonly ParamDescriptor[];
