import { AI_EVIDENCE_LEVEL_CODES } from './registry.enums.const';
import type { ParamDescriptor } from './registry.types';

/**
 * Часть реестра: политики витрины и контура — рычаги, блок «Внимание»,
 * алерты, получатели, доказательность, журнал событий и ручной аудит
 * (план §2.1: lever_params, attention_params, alert_params, rop_user_ids,
 * evidence_gate, portal_events, audit_samples). Собирается в
 * `registry.const.ts`.
 */
export const AI_ANALYTICS_POLICY_PARAMS = [
    {
        code: 'lever_min_section_calls',
        title: 'Минимум разборов раздела для рычага качества',
        scope: 'global',
        source: 'configured',
        unit: 'разборов',
        defaultValue: 20,
        range: [10, 50],
        phase: 2,
        breaksSeries: false,
        description:
            'Рычаг «подтянуть раздел» предлагается только при таком числе разборов раздела у менеджера (расщепление lever_params): меньше — эффект раздела неотличим от шума оценщика.',
    },
    {
        code: 'lever_samples',
        title: 'Сэмплов апостериора для эффекта рычага',
        scope: 'global',
        source: 'configured',
        unit: 'сэмплов',
        defaultValue: 2000,
        range: [500, 10000],
        phase: 2,
        breaksSeries: false,
        description:
            'Сколько сэмплов из апостериоров рёбер и β берётся для интервала ожидаемого прироста продаж (расщепление lever_params); поток задаётся детерминированным seed, поэтому recompute воспроизводит числа.',
    },
    {
        code: 'attention_max_items',
        title: 'Размер блока «Внимание»',
        scope: 'portal',
        source: 'configured',
        unit: 'пунктов',
        defaultValue: 7,
        range: [3, 10],
        phase: 1,
        breaksSeries: false,
        description:
            'Сколько пунктов показывает блок «Внимание» руководителю (расщепление attention_params): остальные сигналы обрезаются по приоритету, чтобы список читался, а не листался.',
    },
    {
        code: 'attention_discipline_pct',
        title: 'Порог дисциплины плана CRM',
        scope: 'portal',
        source: 'configured',
        unit: '%',
        defaultValue: 50,
        range: [30, 80],
        phase: 1,
        breaksSeries: false,
        description:
            'Доля запланированных в CRM дел, выполненных в срок, ниже которой менеджер попадает в «Внимание» (расщепление attention_params).',
    },
    {
        code: 'attention_n_plan_min',
        title: 'Минимум дел для сигнала дисциплины',
        scope: 'portal',
        source: 'configured',
        unit: 'дел в CRM',
        defaultValue: 10,
        range: [5, 30],
        phase: 1,
        breaksSeries: false,
        description:
            'Сигнал дисциплины плана ставится только при таком числе запланированных дел за период (расщепление attention_params): три дела из пяти — не «60 % дисциплины».',
    },
    {
        code: 'attention_no_next_step_streak',
        title: 'Серия звонков без даты следующего контакта',
        scope: 'portal',
        source: 'configured',
        unit: 'звонков подряд',
        defaultValue: 5,
        range: [3, 10],
        phase: 1,
        breaksSeries: false,
        description:
            'Сколько разобранных звонков подряд без следующего шага дают сигнал «не договаривается о следующем контакте» (расщепление attention_params).',
    },
    {
        code: 'alert_max_per_day',
        title: 'Лимит алертов руководителю в день',
        scope: 'portal',
        source: 'configured',
        unit: 'алертов в день',
        defaultValue: 5,
        range: [1, 20],
        phase: 1,
        breaksSeries: false,
        description:
            'Верхняя граница риск-алертов (обещание, конфликт, комплаенс, негатив клиента, срочное) в день на портал (расщепление alert_params); остальное уходит в дайджест.',
    },
    {
        code: 'alert_quiet_from_hour',
        title: 'Начало тихих часов алертов',
        scope: 'portal',
        source: 'configured',
        unit: 'час суток (0–23)',
        defaultValue: 20,
        range: [0, 23],
        phase: 1,
        breaksSeries: false,
        description:
            'С этого часа по времени портала алерты не отправляются, а копятся до конца тихих часов (расщепление alert_params, дефолт 20:00–08:00).',
    },
    {
        code: 'alert_quiet_to_hour',
        title: 'Конец тихих часов алертов',
        scope: 'portal',
        source: 'configured',
        unit: 'час суток (0–23)',
        defaultValue: 8,
        range: [0, 23],
        phase: 1,
        breaksSeries: false,
        description:
            'Час, с которого накопленные за ночь алерты отправляются руководителю (расщепление alert_params); интервал через полночь допустим.',
    },
    {
        code: 'portal_events',
        title: 'Журнал событий портала',
        scope: 'portal',
        source: 'configured',
        unit: 'JSON-массив {date, kind, note, source}',
        defaultValue: '[]',
        phase: 2,
        breaksSeries: false,
        kind: 'json',
        description:
            'Смена цены, акция, скрипт, новичок, смена рубрики (авто), загруженный период, выставка — метки для diff-in-diff и защиты от ложных трендов; автособытия settings_break пишет сохранение настроек. Санити: событие без сдвига ряда за два цикла предлагается удалить.',
    },
    {
        code: 'rop_user_ids',
        title: 'Получатели повестки и алертов',
        scope: 'portal',
        source: 'configured',
        unit: 'Bitrix-id через запятую',
        defaultValue: '',
        phase: 1,
        breaksSeries: false,
        kind: 'csv',
        description:
            'Руководители отдела продаж — периметр прав витрины и адресаты повестки; пустая строка означает «не отправлять». Только id из периметра портала.',
    },
    {
        code: 'evidence_gate_advice',
        title: 'Уровень доказательности для совета «что менять»',
        scope: 'portal',
        source: 'configured',
        unit: 'уровень E0–E3',
        defaultValue: 'E2',
        phase: 2,
        breaksSeries: false,
        kind: 'enum',
        enumValues: AI_EVIDENCE_LEVEL_CODES,
        description:
            'Минимальный уровень для рекомендации «что изменить» (расщепление evidence_gate): E2 — пул порталов или квази-эксперимент. Портал может только ужесточить глобальный дефолт.',
    },
    {
        code: 'evidence_gate_card',
        title: 'Уровень доказательности для описательных карточек',
        scope: 'portal',
        source: 'configured',
        unit: 'уровень E0–E3',
        defaultValue: 'E0',
        phase: 2,
        breaksSeries: false,
        kind: 'enum',
        enumValues: AI_EVIDENCE_LEVEL_CODES,
        description:
            'Минимальный уровень для описательной карточки (расщепление evidence_gate): факт E0 или ассоциация с дизайном E1 показываются без претензии на причинность.',
    },
    {
        code: 'audit_samples_per_month',
        title: 'Ручной аудит: звонков с лучшими баллами в месяц',
        scope: 'portal',
        source: 'configured',
        unit: 'звонков в месяц',
        defaultValue: 30,
        range: [10, 100],
        phase: 3,
        breaksSeries: false,
        description:
            'Сколько звонков с наивысшими оценками руководитель слушает в месяц для проверки оценщика (расщепление audit_samples); результат идёт в ICC и детектор Goodhart.',
    },
    {
        code: 'audit_samples_per_manager',
        title: 'Ручной аудит: звонков на менеджера в месяц',
        scope: 'portal',
        source: 'configured',
        unit: 'звонков на менеджера',
        defaultValue: 4,
        range: [3, 5],
        phase: 3,
        breaksSeries: false,
        description:
            'Минимум прослушанных звонков каждого менеджера в месяц (расщепление audit_samples), чтобы аудит не сводился к лучшим звонкам одного-двух людей.',
    },
] as const satisfies readonly ParamDescriptor[];
