import type { ParamDescriptor } from './registry.types';

/**
 * Часть реестра: экспозиция, усадка норм и шум оценщика
 * (план 4.2–4.3, анкета Ж). Собирается в `registry.const.ts`.
 */
export const AI_ANALYTICS_NORM_PARAMS = [
    {
        code: 'absence_proxy_min_run',
        title: 'Серия нулевых дней для прокси-отсутствия',
        scope: 'global',
        source: 'configured',
        unit: 'рабочих дней подряд',
        defaultValue: 3,
        range: [2, 10],
        phase: 2,
        breaksSeries: false,
        description:
            'Отсутствие проставляется только сериям из стольких нулевых дней подряд; одиночные нулевые дни остаются в знаменателе D_mt и показываются отдельной метрикой дисциплины «простойные дни».',
    },
    {
        code: 'min_workdays_month',
        title: 'Минимум рабочих дней в месяце для норм',
        scope: 'global',
        source: 'configured',
        unit: 'рабочих дней',
        defaultValue: 8,
        range: [5, 12],
        phase: 2,
        breaksSeries: false,
        description:
            'Менеджер-месяцы с D_mt ниже порога или с daysSource = proxy исключаются из оценки норм μ, силы усадки κ и capacity; у самого менеджера показываются с подписью.',
    },
    {
        code: 'forget_lambda',
        title: 'Коэффициент забывания месяцев λ',
        scope: 'global',
        source: 'configured',
        unit: 'коэффициент',
        defaultValue: 0.85,
        range: [0.6, 0.97],
        phase: 2,
        breaksSeries: false,
        description:
            'Вес месяца в накопленных Ñ, D̃, s̃, ñ равен λ в степени числа месяцев назад; память ≈ 1/(1 − λ) ≈ 6,7 месяца при дефолте 0,85.',
    },
    {
        code: 'overdispersion_default',
        title: 'Сверхдисперсия темпов активностей φ до оценки',
        scope: 'portal',
        source: 'hybrid',
        unit: 'коэффициент',
        defaultValue: 2.5,
        range: [1, 6],
        phase: 2,
        breaksSeries: false,
        prior: 2.5,
        estimator: 'квази-Пуассон по остаткам менеджер × тип активности',
        minN: 12,
        gate: '≥ 12 недель данных менеджер × тип',
        description:
            'Во сколько раз дисперсия числа активностей выше пуассоновской; делит экспозицию в апостериоре темпа (Ñ/φ, D̃/φ) и нормирует остатки для CUSUM.',
    },
    {
        code: 'kappa_activity_days',
        title: 'Сила усадки нормы темпа κ_a',
        scope: 'portal',
        source: 'hybrid',
        unit: 'рабочих дней',
        defaultValue: 20,
        range: [5, 120],
        phase: 2,
        breaksSeries: false,
        prior: 20,
        estimator: 'Клейнман по методу моментов на log-шкале',
        minN: 5,
        gate: '≥ 6 мес. истории и ≥ 5 менеджеров портала',
        description:
            'Псевдонаблюдения в рабочих днях в формуле E[a_mk] = (Ñ/φ + κ_a·μ_lk)/(D̃/φ + κ_a): при 20 днях менеджер с месяцем данных берёт около половины веса от собственных чисел.',
    },
    {
        code: 'kappa_edge_early',
        title: 'Сила усадки ранних рёбер воронки',
        scope: 'portal',
        source: 'hybrid',
        unit: 'псевдонаблюдений знаменателя',
        defaultValue: 100,
        range: [5, 500],
        phase: 2,
        breaksSeries: false,
        prior: 100,
        estimator: 'Клейнман: κ̂ = clip((1 − ρ̂)/ρ̂, 5, kappa_max)',
        minN: 5,
        gate: '≥ 6 мес. истории и ≥ 5 менеджеров портала',
        description:
            'κ_k для рёбер с большим знаменателем (E1 «звонок → презентация», E3′): до гейта Клейнмана менеджеру нужно около 100 входов ребра, чтобы перевесить норму слоя.',
    },
    {
        code: 'kappa_edge_late',
        title: 'Сила усадки поздних рёбер воронки',
        scope: 'portal',
        source: 'hybrid',
        unit: 'псевдонаблюдений знаменателя',
        defaultValue: 30,
        range: [5, 500],
        phase: 2,
        breaksSeries: false,
        prior: 30,
        estimator: 'Клейнман: κ̂ = clip((1 − ρ̂)/ρ̂, 5, kappa_max)',
        minN: 5,
        gate: '≥ 6 мес. истории и ≥ 5 менеджеров портала',
        description:
            'κ_k для рёбер с малым знаменателем (E2–E5: КП, счета, продажи), где 30 входов уже дают половину веса собственным числам менеджера.',
    },
    {
        code: 'kappa_max',
        title: 'Потолок силы усадки κ',
        scope: 'global',
        source: 'configured',
        unit: 'псевдонаблюдений знаменателя',
        defaultValue: 500,
        range: [100, 2000],
        phase: 2,
        breaksSeries: false,
        description:
            'Верхняя граница clip для оценки Клейнмана; при ρ̂ ≤ 0 (разброс ниже биномиального — менеджеры однородны) берётся ровно это значение с пометкой «полная усадка».',
    },
    {
        code: 'kappa_layer_ratio',
        title: 'Доля типичной экспозиции слоя в силе усадки ρ_κ',
        scope: 'global',
        source: 'configured',
        unit: 'доля',
        defaultValue: 0.4,
        range: [0.1, 1],
        phase: 2,
        breaksSeries: false,
        description:
            'Силы усадки слоёв — не константы, а доля медианной экспозиции: κ_level,k = ρ_κ·median(ñ_mk), κ_portal,k = ρ_κ·median(ñ_pk); для E1 это ≈ 120 звонков, для E4 ≈ 3 счёта.',
    },
    {
        code: 'kappa_portal_to_global',
        title: 'Сила усадки нормы портала к глобальному пулу',
        scope: 'global',
        source: 'configured',
        unit: 'псевдонаблюдений знаменателя',
        defaultValue: 0,
        range: [0, 300],
        phase: 4,
        breaksSeries: false,
        description:
            'Решение владельца А.3: пула порталов нет, poolOptIn = false, поэтому усадка к глобальному слою выключена (0) — верхний слой одно-портального режима это сам портал по leave-one-out.',
    },
    {
        code: 'kappa_boot_ratio',
        title: 'Доля экспозиции в стартовой усадке нового портала',
        scope: 'global',
        source: 'configured',
        unit: 'доля',
        defaultValue: 0.2,
        range: [0, 1],
        phase: 2,
        breaksSeries: false,
        description:
            'κ_boot = kappa_boot_ratio·median(ñ): дефолты рёбер из дампа влияют только на новый портал в первые ≤ 3 месяца и вытесняются его собственными данными.',
    },
    {
        code: 'm_s_default',
        title: 'Псевдо-n усадки качества m_S до оценки',
        scope: 'portal',
        source: 'hybrid',
        unit: 'разборов',
        defaultValue: 10,
        range: [2, 100],
        phase: 2,
        breaksSeries: false,
        prior: 10,
        estimator: 'ANOVA по менеджерам портала: m_S = σ²_within/τ²_between',
        minN: 20,
        gate: '≥ 5 менеджеров с n ≥ 20 разборов',
        description:
            'Сила усадки средней оценки к норме полосы в Normal-Normal: Ŝ_mj = (n_mj·S̄_mj + m_S·μ_lj)/(n_mj + m_S).',
    },
    {
        code: 'm_s_max',
        title: 'Потолок псевдо-n усадки качества',
        scope: 'global',
        source: 'configured',
        unit: 'разборов',
        defaultValue: 50,
        range: [10, 200],
        phase: 2,
        breaksSeries: false,
        description:
            'Если ANOVA даёт τ̂² ≤ 0 (менеджеры по качеству неразличимы), m_S берётся равным потолку и оценки полностью стягиваются к норме с явной пометкой.',
    },
    {
        code: 'sigma_llm_default',
        title: 'Шум LLM-оценщика σ_llm до измерения',
        scope: 'global',
        source: 'hybrid',
        unit: 'баллов шкалы 1–10',
        defaultValue: 1.2,
        range: [0.3, 3],
        phase: 3,
        breaksSeries: false,
        prior: 1.2,
        estimator: 'test-retest: σ²_llm = ½·mean((S⁽¹⁾ − S⁽²⁾)²)',
        minN: 300,
        gate: 'два прогона на retest_budget_calls разборах при смене версии',
        description:
            'Входит в SE(S̄) = √((σ²_skill + σ²_llm)/n); до измерения карточки несут подпись «надёжность не измерена», величина эффекта качества скрыта.',
    },
    {
        code: 's_ref',
        title: 'Референсное качество S_ref',
        scope: 'tenure',
        source: 'estimated',
        unit: 'баллов шкалы 1–10',
        defaultValue: 7,
        range: [3, 9],
        phase: 2,
        breaksSeries: false,
        estimator: 'медиана Ŝ полосы стажа 6–18 мес. за 3 месяца',
        minN: 20,
        gate: '≥ 3 менеджера полосы с n ≥ n_min_ok_score',
        description:
            'Точка отсчёта отношения r(S) = p̂(S)/p̂(S_ref) и обратной задачи плана; до накопления данных берётся 7 с подписью «референс не оценён».',
    },
] as const satisfies readonly ParamDescriptor[];
