export enum EBxNamespace {
    CRM = 'crm',
    TASKS = 'tasks',
    LISTS = 'lists',
    CRM_ITEM = 'crm.item',
    WITHOUT_NAMESPACE = 'without.namespace',
    DISK = 'disk',
    CATALOG = 'catalog',
    RPA = 'rpa',
    IM = 'im',
}

export enum EBxMethod {
    ADD = 'add',
    SET = 'set',
    UPDATE = 'update',
    GET = 'get',
    USER_FIELD_LIST = 'userfield.list',
    USER_FIELD_GET = 'userfield.get',
    USER_FIELD_ADD = 'userfield.add',
    LIST = 'list',
    DELETE = 'delete',
    CONTACT_ITEMS_SET = 'contact.items.set',
    CONTACT_ADD = 'contact.add',
    CONTACT_ITEMS_GET = 'contact.items.get',
    FIELD_GET = 'field.get',
    FIELDS = 'fields',
    GET_BY_ENTITY_TYPE_ID = 'getByEntityTypeId',

    FILES_ATTACH = 'files.attach',
    DELEGATE = 'delegate',
    COUNTERS_GET = 'counters.get',
    START = 'start',
    PAUSE = 'pause',
    DEFER = 'defer',
    COMPLETE = 'complete',
    RENEW = 'renew',
    APPROVE = 'approve',
    DISAPPROVE = 'disapprove',
    STARTWATCH = 'startwatch',
    STOPWATCH = 'stopwatch',
    FAVORITE_ADD = 'favorite.add',
    FAVORITE_REMOVE = 'favorite.remove',
    GET_FIELDS = 'getFields',
    GET_ACCESS = 'getaccess',
    HISTORY_LIST = 'history.list',
    MUTE = 'mute',
    UNMUTE = 'unmute',
}
