export enum EBxNamespace {
    CRM = 'crm',
    IMV2 = 'im.v2',
    TASKS = 'tasks',
    TASK = 'task',
    LISTS = 'lists',
    CRM_ITEM = 'crm.item',
    WITHOUT_NAMESPACE = 'without.namespace',
    DISK = 'disk',
    CATALOG = 'catalog',
    RPA = 'rpa',
    IM = 'im',
    USER = 'user',
    BIZPROC = 'bizproc',
    IMBOT = 'imbot',
    IMBOT_V2 = 'imbot.v2',
    IMOPENLINES = 'imopenlines',
    SONET_GROUP = 'sonet_group',
}

export enum EBxMethod {
    ADD = 'add',
    SUBSCRIBE = 'subscribe',
    SET = 'set',
    UPDATE = 'update',
    UPDATE_COLOR = 'updateColor',
    UPDATE_DEADLINE = 'updateDeadline',
    UPDATE_DESCRIPTION = 'updateDescription',
    UPDATE_RESPONSIBLE_USER = 'updateResponsibleUser',
    GET = 'get',

    USER_FIELD_LIST = 'userfield.list',
    USER_FIELD_GET = 'userfield.get',
    USER_FIELD_ADD = 'userfield.add',
    USER_FIELD_UPDATE = 'userfield.update',
    USER_FIELD_DELETE = 'userfield.delete',
    LIST = 'list',
    DELETE = 'delete',

    CONTACT_ITEMS_SET = 'contact.items.set',
    CONTACT_ADD = 'contact.add',
    CONTACT_ITEMS_GET = 'contact.items.get',
    CONTACT_ITEMS_DELETE = 'contact.items.delete',

    FIELD_GET = 'field.get',
    FIELDS = 'fields',
    GET_BY_ENTITY_TYPE_ID = 'getByEntityTypeId',
    GET_LIST = 'getlist',

    // crm.status.entity.*
    ENTITY_ITEMS = 'entity.items',
    ENTITY_TYPES = 'entity.types',

    // RPA stage methods (rpa.stage.*)
    STAGE_ADD = 'stage.add',
    STAGE_UPDATE = 'stage.update',
    STAGE_LIST_FOR_TYPE = 'stage.listForType',

    // Lists field methods (lists.field.*)
    FIELD_ADD = 'field.add',
    FIELD_UPDATE = 'field.update',
    FIELD_DELETE = 'field.delete',

    // CRM enum
    ENUM_OWNER_TYPE = 'enum.ownertype',

    // Tasks
    FILES_ATTACH = 'files.attach',
    DELEGATE = 'delegate',
    COUNTERS_GET = 'counters.get',
    START = 'start',
    PAUSE = 'pause',
    DEFER = 'defer',
    COMPLETE = 'complete',
    RENEW = 'renew',
    APPROVE = 'approve',
    DISAPPROVE = 'disapprove',
    STARTWATCH = 'startwatch',
    STOPWATCH = 'stopwatch',
    FAVORITE_ADD = 'favorite.add',
    FAVORITE_REMOVE = 'favorite.remove',
    GET_FIELDS = 'getFields',
    GET_ACCESS = 'getaccess',
    HISTORY_LIST = 'history.list',
    MUTE = 'mute',
    UNMUTE = 'unmute',
    SEARCH = 'search',
    CURRENT = 'current',
    DIALOG_GET = 'dialog.get',

    // Disk
    MOVE_TO = 'moveto',
    RESTORE = 'restore',
    GET_TYPES = 'gettypes',
    GET_CHILDREN = 'getchildren',
    GET_VERSIONS = 'getVersions',
    MARK_DELETED = 'markdeleted',
    COPY_TO = 'copyto',
    GET_EXTERNAL_LINK = 'getExternalLink',
    GET_EXTERNAL_LINK_LOWER = 'getexternallink',
    RENAME = 'rename',
    UPLOAD_FILE = 'uploadfile',
    UPLOAD_VERSION = 'uploadversion',
    RESTORE_FROM_VERSION = 'restoreFromVersion',
    ADD_FOLDER = 'addfolder',
    ADD_SUBFOLDER = 'addsubfolder',
    SHARE_TO_USER = 'sharetouser',
    DELETE_TREE = 'deletetree',
    PIN = 'pin',

    // Chat bots (imbot.* / imbot.v2.* / imopenlines.*)
    REGISTER = 'register',
    UNREGISTER = 'unregister',
    ANSWER = 'answer',
    LIKE = 'like',
    LEAVE = 'leave',
    SEND = 'send',
    SEND_TYPING = 'sendTyping',
    SET_OWNER = 'setOwner',
    SET_MANAGER = 'setManager',
    UPDATE_TITLE = 'updateTitle',
    UPDATE_AVATAR = 'updateAvatar',
    USER_ADD = 'user.add',
    USER_DELETE = 'user.delete',
    USER_LIST = 'user.list',
    MANAGER_ADD = 'manager.add',
    MANAGER_DELETE = 'manager.delete',
    GET_CONTEXT = 'getContext',
    READ = 'read',
    REACTION_ADD = 'Reaction.add',
    REACTION_DELETE = 'Reaction.delete',
    UPLOAD = 'upload',
    DOWNLOAD = 'download',
    UNSUBSCRIBE = 'unsubscribe',
    INPUT_ACTION_NOTIFY = 'inputAction.notify',
    TEXT_FIELD_ENABLED = 'textField.enabled',
    REVISION_GET = 'revision.get',
    // entity = 'bot.session', поэтому методы — голые (imopenlines.bot.session.finish)
    SESSION_FINISH = 'finish',
    SESSION_TRANSFER = 'transfer',
    SESSION_OPERATOR = 'operator',
    SESSION_MESSAGE_SEND = 'message.send',
}
