export enum EBXEntity {
    DEAL = 'deal',
    COMPANY = 'company',
    CONTACT = 'contact',
    LEAD = 'lead',
    TASK = 'task',
    ITEM = 'item',
    ELEMENT = 'element',
    TYPE = 'type',
    TIMELINE_COMMENT = 'timeline.comment',
    PRODUCT_ROW = 'productrow',
    USER_FIELD = 'userfield',
    USER_FIELD_CONFIG = 'userfieldconfig',
    USER_FIELD_ENUMERATION = 'userfield.enumeration',
    LISTS = 'lists',
    ACTIVITY = 'activity',
    ACTIVITY_TODO = 'activity.todo',
    FILE = 'file',
    CATEGORY = 'category',
    STATUS = 'status',
    STAGE = 'stage',
    PRODUCT = 'product',
    RPA = 'rpa',
    REQUISITE = 'requisite',
    RECENT = 'recent',
    MESSAGE = 'message',
    DIALOG_MESSAGES = 'dialog.messages',
    EVENT = 'Event',
    USER = 'user',
    CHAT = 'chat',
    DIALOG = 'dialog',
    FOLDER = 'folder',
    STORAGE = 'storage',
    WORKFLOW = 'workflow',
    CHECKLIST_ITEM = 'checklistitem',

    // Chat bots
    BOT = 'bot',
    BOT_LIFECYCLE = '', // entity-less методы: imbot.register / imbot.unregister / imbot.update
    COMMAND = 'command',
    // imbot.v2 — сущности с PascalCase, как требует REST-строка метода
    BOT_V2 = 'Bot',
    CHAT_V2 = 'Chat',
    COMMAND_V2 = 'Command',
    CHAT_MESSAGE_V2 = 'Chat.Message',
    REVISION = 'revision',
    // imopenlines
    BOT_SESSION = 'bot.session',
}
