export type PbxDealSalesBaseCategoryType = {
    "id": 0,
    "entityTypeId": 2,
    "entityType": "deal",
    "type": "deal",
    "group": "sales",
    "name": "ОП Основная",
    "title": "ОП Основная",
    "bitrixId": "",
    "bitrixCamelId": "",
    "code": "sales_base",
    "isActive": true,
    "order": 1,
    "isNeedUpdate": true,
    "isDefault": "N",
    "stages": [
        {
            "id": 0,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Новая",
            "title": "Новая",
            "bitrixId": "NEW",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#eef0e6",
            "code": "sales_new",
            "isNeedUpdate": true,
            "order": 1,
            "isDefault": "Y"
        },
        {
            "id": 1,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Холодные",
            "title": "Холодные",
            "bitrixId": "COLD",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#3bc8f5",
            "code": "sales_cold",
            "isNeedUpdate": true,
            "order": 2,
            "isDefault": "N"
        },
        {
            "id": 2,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Переговоры",
            "title": "Переговоры",
            "bitrixId": "WARM",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#0ec96f",
            "code": "sales_warm",
            "isNeedUpdate": true,
            "order": 3,
            "isDefault": "N"
        },
        {
            "id": 3,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Презентация",
            "title": "Презентация",
            "bitrixId": "PRESENTATION",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#fff300",
            "code": "sales_pres",
            "isNeedUpdate": true,
            "order": 4,
            "isDefault": "N"
        },
        {
            "id": 4,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Документы",
            "title": "Документы",
            "bitrixId": "OFFER_CREATE",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#8e5cbf",
            "code": "sales_offer_create",
            "isNeedUpdate": true,
            "order": 5,
            "isDefault": "N"
        },
        {
            "id": 5,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Отправлены",
            "title": "Отправлены",
            "bitrixId": "DOCUMENT_SEND",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#683699",
            "code": "sales_document_send",
            "isNeedUpdate": true,
            "order": 6,
            "isDefault": "N"
        },
        {
            "id": 6,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "В решении",
            "title": "В решении",
            "bitrixId": "IN_PROSRESS",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#f0008c",
            "code": "sales_in_progress",
            "isNeedUpdate": true,
            "order": 7,
            "isDefault": "N"
        },
        {
            "id": 7,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "В оплате",
            "title": "В оплате",
            "bitrixId": "MONEY_AWAIT",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#a0005c",
            "code": "sales_money_await",
            "isNeedUpdate": true,
            "order": 8,
            "isDefault": "N"
        },
        {
            "id": 8,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Поставка",
            "title": "Поставка",
            "bitrixId": "SUPPLY_INIT",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#0070bf",
            "code": "sales_supply",
            "isNeedUpdate": true,
            "order": 9,
            "isDefault": "N"
        },
        {
            "id": 9,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Успех",
            "title": "Успех",
            "bitrixId": "WON",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#00ff00",
            "code": "sales_success",
            "isNeedUpdate": true,
            "order": 10,
            "isDefault": "N"
        },
        {
            "id": 10,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Отказ",
            "title": "Отказ",
            "bitrixId": "LOSE",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#e7354a",
            "code": "sales_fail",
            "isNeedUpdate": true,
            "order": 11,
            "isDefault": "N"
        },
        {
            "id": 11,
            "categoryId": 0,
            "entityType": "deal",
            "parentType": "sales",
            "type": "deal",
            "group": "sales",
            "name": "Не состоялась",
            "title": "Не состоялась",
            "bitrixId": "APOLOGY",
            "isActive": true,
            "smartBitrixId": "DEAL_STAGE",
            "color": "#2d0b0d",
            "code": "sales_double",
            "isNeedUpdate": true,
            "order": 12,
            "isDefault": "N"
        }
    ]
}
