import { Address } from './bx-address.type';
import { Bank } from './bx-bank.type';
import { CustomField } from './bx-custom-field.type';

export class BXRequisiteDTO {
    ID: number;
    ENTITY_TYPE_ID?: number | null;
    ENTITY_ID: number;
    PRESET_ID?: number | null;
    DATE_CREATE?: string | null;
    DATE_MODIFY?: string | null;
    CREATED_BY_ID?: number | null;
    MODIFY_BY_ID?: number | null;
    NAME?: string | null;
    CODE?: string | null;
    XML_ID?: string | null;
    ORIGINATOR_ID?: string | null;
    ACTIVE?: string | null;
    ADDRESS_ONLY?: string | null;
    SORT?: number | null;
    RQ_NAME?: string | null;
    RQ_FIRST_NAME?: string | null;
    RQ_LAST_NAME?: string | null;
    RQ_SECOND_NAME?: string | null;
    RQ_COMPANY_ID?: string | null;
    RQ_COMPANY_NAME?: string | null;
    RQ_COMPANY_FULL_NAME?: string | null;
    RQ_COMPANY_REG_DATE?: string | null;
    RQ_DIRECTOR?: string | null;
    RQ_DIRECTOR_CASE?: string | null;
    RQ_POSITION?: string | null;
    RQ_POSITION_CASE?: string | null;
    RQ_BASED?: string | null;
    RQ_BASED_CASE?: string | null;
    RQ_BASE_OTHER: string | null;
    RQ_ACCOUNTANT?: string | null;
    RQ_CEO_NAME?: string | null;
    RQ_CEO_WORK_POS?: string | null;
    RQ_CONTACT?: string | null;
    RQ_EMAIL?: string | null;
    RQ_PHONE?: string | null;
    RQ_FAX?: string | null;
    RQ_IDENT_TYPE?: string | null;
    RQ_IDENT_DOC?: string | null;
    RQ_IDENT_DOC_SER?: string | null;
    RQ_IDENT_DOC_NUM?: string | null;
    RQ_IDENT_DOC_PERS_NUM?: string | null;
    RQ_IDENT_DOC_DATE?: string | null;
    RQ_IDENT_DOC_ISSUED_BY?: string | null;
    RQ_IDENT_DOC_DEP_CODE?: string | null;
    RQ_INN?: string | null;
    RQ_KPP?: string | null;
    RQ_USRLE?: string | null;
    RQ_IFNS?: string | null;
    RQ_OGRN?: string | null;
    RQ_OGRNIP?: string | null;
    RQ_OKPO?: string | null;
    RQ_OKTMO?: string | null;
    RQ_OKVED?: string | null;
    RQ_EDRPOU?: string | null;
    RQ_DRFO?: string | null;
    RQ_KBE?: string | null;
    RQ_IIN?: string | null;
    RQ_BIN?: string | null;
    RQ_ST_CERT_SER?: string | null;
    RQ_ST_CERT_NUM?: string | null;
    RQ_ST_CERT_DATE?: string | null;
    RQ_VAT_PAYER?: string | null;
    RQ_VAT_ID?: string | null;
    RQ_VAT_CERT_SER?: string | null;
    RQ_VAT_CERT_NUM?: string | null;
    RQ_VAT_CERT_DATE?: string | null;
    RQ_RESIDENCE_COUNTRY?: string | null;
    RQ_BASE_DOC?: string | null;
    RQ_REGON?: string | null;
    RQ_KRS?: string | null;
    RQ_PESEL?: string | null;
    RQ_LEGAL_FORM?: string | null;
    RQ_SIRET?: string | null;
    RQ_SIREN?: string | null;
    RQ_CAPITAL?: string | null;
    RQ_RCS?: string | null;
    RQ_CNPJ?: string | null;
    RQ_STATE_REG?: string | null;
    RQ_MNPL_REG?: string | null;
    RQ_CPF?: string | null;
    customFields?: CustomField[] | null;
    address?: Address[] | null;
    bank?: Bank[] | null;

    constructor(data: Partial<BXRequisiteDTO>) {
        this.ID = data.ID || 0;
        this.ENTITY_TYPE_ID = data.ENTITY_TYPE_ID ?? null;
        this.ENTITY_ID = data.ENTITY_ID || 0;
        this.PRESET_ID = data.PRESET_ID ?? null;
        this.DATE_CREATE = data.DATE_CREATE ?? null;
        this.DATE_MODIFY = data.DATE_MODIFY ?? null;
        this.CREATED_BY_ID = data.CREATED_BY_ID ?? null;
        this.MODIFY_BY_ID = data.MODIFY_BY_ID ?? null;
        this.NAME = data.NAME ?? null;
        this.CODE = data.CODE ?? null;
        this.XML_ID = data.XML_ID ?? null;
        this.ORIGINATOR_ID = data.ORIGINATOR_ID ?? null;
        this.ACTIVE = data.ACTIVE ?? null;
        this.ADDRESS_ONLY = data.ADDRESS_ONLY ?? null;
        this.SORT = data.SORT ?? null;
        this.RQ_NAME = data.RQ_NAME ?? '';
        this.RQ_FIRST_NAME = data.RQ_FIRST_NAME ?? '';
        this.RQ_LAST_NAME = data.RQ_LAST_NAME ?? '';
        this.RQ_SECOND_NAME = data.RQ_SECOND_NAME ?? '';
        this.RQ_COMPANY_ID = data.RQ_COMPANY_ID ?? '';
        this.RQ_COMPANY_NAME = data.RQ_COMPANY_NAME ?? '';
        this.RQ_COMPANY_FULL_NAME = data.RQ_COMPANY_FULL_NAME ?? '';
        this.RQ_COMPANY_REG_DATE = data.RQ_COMPANY_REG_DATE ?? '';
        this.RQ_DIRECTOR = data.RQ_DIRECTOR ?? '';
        this.RQ_DIRECTOR_CASE = data.RQ_DIRECTOR_CASE ?? '';
        this.RQ_POSITION = data.RQ_POSITION ?? '';
        this.RQ_POSITION_CASE = data.RQ_POSITION_CASE ?? '';
        this.RQ_BASED = data.RQ_BASED ?? '';
        this.RQ_BASED_CASE = data.RQ_BASED_CASE ?? '';
        this.RQ_BASE_OTHER = data.RQ_BASE_OTHER ?? ''; // Дополнительные реквизиты кастомное поле
        // this['1773131028'] = data['1773131028'] ?? '';  // Дополнительные реквизиты кастомное поле

        this.RQ_ACCOUNTANT = data.RQ_ACCOUNTANT ?? '';
        this.RQ_CEO_NAME = data.RQ_CEO_NAME ?? '';
        this.RQ_CEO_WORK_POS = data.RQ_CEO_WORK_POS ?? '';
        this.RQ_CONTACT = data.RQ_CONTACT ?? '';
        this.RQ_EMAIL = data.RQ_EMAIL ?? '';
        this.RQ_PHONE = data.RQ_PHONE ?? '';
        this.RQ_FAX = data.RQ_FAX ?? '';
        this.RQ_IDENT_TYPE = data.RQ_IDENT_TYPE ?? '';
        this.RQ_IDENT_DOC = data.RQ_IDENT_DOC ?? '';
        this.RQ_IDENT_DOC_SER = data.RQ_IDENT_DOC_SER ?? '';
        this.RQ_IDENT_DOC_NUM = data.RQ_IDENT_DOC_NUM ?? '';
        this.RQ_IDENT_DOC_PERS_NUM = data.RQ_IDENT_DOC_PERS_NUM ?? '';
        this.RQ_IDENT_DOC_DATE = data.RQ_IDENT_DOC_DATE ?? '';
        this.RQ_IDENT_DOC_ISSUED_BY = data.RQ_IDENT_DOC_ISSUED_BY ?? '';
        this.RQ_IDENT_DOC_DEP_CODE = data.RQ_IDENT_DOC_DEP_CODE ?? '';
        this.RQ_INN = data.RQ_INN ?? '';
        this.RQ_KPP = data.RQ_KPP ?? '';
        this.RQ_USRLE = data.RQ_USRLE ?? '';
        this.RQ_IFNS = data.RQ_IFNS ?? '';
        this.RQ_OGRN = data.RQ_OGRN ?? '';
        this.RQ_OGRNIP = data.RQ_OGRNIP ?? '';
        this.RQ_OKPO = data.RQ_OKPO ?? '';
        this.RQ_OKTMO = data.RQ_OKTMO ?? '';
        this.RQ_OKVED = data.RQ_OKVED ?? '';
        this.RQ_EDRPOU = data.RQ_EDRPOU ?? '';
        this.RQ_DRFO = data.RQ_DRFO ?? '';
        this.RQ_KBE = data.RQ_KBE ?? '';
        this.RQ_IIN = data.RQ_IIN ?? '';
        this.RQ_BIN = data.RQ_BIN ?? '';
        this.RQ_ST_CERT_SER = data.RQ_ST_CERT_SER ?? '';
        this.RQ_ST_CERT_NUM = data.RQ_ST_CERT_NUM ?? '';
        this.RQ_ST_CERT_DATE = data.RQ_ST_CERT_DATE ?? '';
        this.RQ_VAT_PAYER = data.RQ_VAT_PAYER ?? '';
        this.RQ_VAT_ID = data.RQ_VAT_ID ?? '';
        this.RQ_VAT_CERT_SER = data.RQ_VAT_CERT_SER ?? '';
        this.RQ_VAT_CERT_NUM = data.RQ_VAT_CERT_NUM ?? '';
        this.RQ_VAT_CERT_DATE = data.RQ_VAT_CERT_DATE ?? '';
        this.RQ_RESIDENCE_COUNTRY = data.RQ_RESIDENCE_COUNTRY ?? '';
        this.RQ_BASE_DOC = data.RQ_BASE_DOC ?? '';
        this.RQ_REGON = data.RQ_REGON ?? '';
        this.RQ_KRS = data.RQ_KRS ?? '';
        this.RQ_PESEL = data.RQ_PESEL ?? '';
        this.RQ_LEGAL_FORM = data.RQ_LEGAL_FORM ?? '';
        this.RQ_SIRET = data.RQ_SIRET ?? '';
        this.RQ_SIREN = data.RQ_SIREN ?? '';
        this.RQ_CAPITAL = data.RQ_CAPITAL ?? '';
        this.RQ_RCS = data.RQ_RCS ?? '';
        this.RQ_CNPJ = data.RQ_CNPJ ?? '';
        this.RQ_STATE_REG = data.RQ_STATE_REG ?? '';
        this.RQ_MNPL_REG = data.RQ_MNPL_REG ?? '';
        this.RQ_CPF = data.RQ_CPF ?? '';
        this.customFields = data.customFields ?? null;
        this.address = data.address ?? null;
        this.bank = data.bank ?? null;
    }
}
