import { EBXTaskMark, IBXDeal, IBXUser } from "src/modules/bitrix/domain/interfaces/bitrix.interface";
import { EV_TYPE, IEventTask } from "../../types/task-types";
import { PresentationStateCount } from "../../types/presentation-types";

export class EventTaskDto implements IEventTask {
    name: string;
    type: EV_TYPE;
    isExpired: "no" | "almost" | "yes";
    eventType: "xo" | "warm" | "presentation" | "in_progress" | "money_await" | "event" | "supply";
    presentation: null | PresentationStateCount;
    dealBase: null | IBXDeal;
    originalEventType?: "presentation" | null;
    isPresentationCanceled?: boolean;
    // IBXTask properties
    accomplices: [];
    accomplicesData: [];
    activityDate: "2017-12-29T13:07:19+03:00";
    addInReport: "N";
    allowChangeDeadline: "Y";
    allowTimeTracking: "N";
    auditors: [];
    auditorsData: [];
    changedBy: "1";
    changedDate: "2017-12-29T13:07:19+03:00";
    closedBy: "81";
    closedDate: "2017-12-29T13:06:18+03:00";
    commentsCount: null;
    createdBy: "1";
    createdDate: "2017-12-29T12:15:42+03:00";
    creator: IBXUser;
    dateStart: "2017-12-29T13:04:29+03:00";
    deadline: "2017-12-29T15:00:00+03:00";
    description: string;
    descriptionInBbcode: "Y";
    durationFact: null;
    durationPlan: null;
    durationType: "days";
    endDatePlan: null;
    exchangeId: null;
    exchangeModified: null;
    favorite: "N";
    forkedByTemplateId: null;
    forumId: null;
    forumTopicId: null;
    group: [];
    groupId: number;
    guid: "{9bd11fb5-8e76-4379-b3be-1f4cbe9bae1d}";
    id: number;
    isMuted: "N";
    isPinned: "N";
    isPinnedInGroup: "N";
    mark: EBXTaskMark;
    matchWorkTime: "N";
    multitask: "N";
    newCommentsCount: 0;
    notViewed: "N";
    outlookVersion: "4";
    parentId: null;
    priority: "0";
    replicate: "N";
    responsible: IBXUser;
    responsibleId: "81";
    serviceCommentsCount: null;
    siteId: "s1";
    sorting: null;
    stageId: "0";
    startDatePlan: null;
    status: "5";
    statusChangedBy: "81";
    statusChangedDate: "2017-12-29T13:06:18+03:00";
    subStatus: "5";
    subordinate: "N";
    taskControl: "N";
    timeEstimate: "0";
    timeSpentInLogs: null;
    title: string;
    viewedDate: "2017-12-29T19:44:28+03:00";
    xmlId: null;
    ufCrmTask: string[];
}
