import { RqSelectItem } from './counter.types';
import { CounterType } from './counter-type.enum';

export function buildCounterFormInitial(
    rqSelect: RqSelectItem[],
    initialValue: RqSelectItem | null,
) {
    return {
        apiName: 'counter',
        title: 'Создание counter',
        entityType: 'entity',
        groups: [
            {
                groupName: 'Поля для Создания counter',
                entityType: 'group',
                isCanAddField: true,
                isCanDeleteField: true,
                fields: [
                    {
                        id: 1,
                        title: 'value',
                        name: 'value',
                        apiName: 'value',
                        type: 'string',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                        isRequired: true,
                    },
                    {
                        id: 2,
                        title: 'type',
                        name: 'type',
                        apiName: 'type',
                        type: 'select',
                        entityType: 'counter',
                        validation: 'required',
                        initialValue: '',
                        items: Object.values(CounterType).map(v => ({
                            value: v,
                            label: v,
                        })),
                        isCanAddField: false,
                        isRequired: true,
                    },
                    {
                        id: 3,
                        title: 'prefix',
                        name: 'prefix',
                        apiName: 'prefix',
                        type: 'string',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                        isRequired: true,
                    },
                    {
                        id: 4,
                        title: 'postfix',
                        name: 'postfix',
                        apiName: 'postfix',
                        type: 'string',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                        isRequired: true,
                    },
                    {
                        id: 5,
                        title: 'name',
                        name: 'name',
                        apiName: 'name',
                        type: 'string',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                        isRequired: true,
                    },
                    {
                        id: 6,
                        title: 'Show Name (title)',
                        name: 'title',
                        apiName: 'title',
                        type: 'string',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                        isRequired: true,
                    },
                    {
                        id: 7,
                        title: 'size',
                        name: 'size',
                        apiName: 'size',
                        type: 'number',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                    },
                    {
                        id: 8,
                        title: 'count',
                        name: 'count',
                        apiName: 'count',
                        type: 'number',
                        entityType: 'counter',
                        validation: 'required|max:255',
                        initialValue: '',
                        isCanAddField: false,
                    },
                    {
                        id: 9,
                        title: 'day',
                        name: 'day',
                        apiName: 'day',
                        type: 'boolean',
                        entityType: 'counter',
                        validation: '',
                        initialValue: false,
                        isCanAddField: false,
                    },
                    {
                        id: 10,
                        title: 'month',
                        name: 'month',
                        apiName: 'month',
                        type: 'boolean',
                        entityType: 'counter',
                        validation: '',
                        initialValue: false,
                        isCanAddField: false,
                    },
                    {
                        id: 11,
                        title: 'year',
                        name: 'year',
                        apiName: 'year',
                        type: 'boolean',
                        entityType: 'counter',
                        validation: '',
                        initialValue: false,
                        isCanAddField: false,
                    },
                    {
                        id: 12,
                        title: 'Relation template_id',
                        name: 'rq_id',
                        apiName: 'rq_id',
                        type: 'select',
                        entityType: 'counter',
                        validation: 'required',
                        initialValue,
                        items: rqSelect,
                        isCanAddField: false,
                    },
                ],
                relations: [],
            },
        ],
    };
}
